### PR TITLE
Add- Adding dark mode to website #112

### LINKED ISSUE #112: Need to add Darkmode for the project
I need to add Dark Mode for the project

### PR DESCRIPTION
**Pull request by 0nikhilkumar**
adding dark mode to the main page or website

Fixes #112 

before :-
whiteMode

after :-
dark mode

How should this be tested?
1. Go on home page
2. On top right there is theme change button

### CODE REVIEW

**Comment by 0nikhilkumar** [comment]
Sir I am hacktoberfest'23 participants so please merge this Pull Request and give the label of "hacktoberfest-accepted" then its counted for merging 1PR in hacktoberfest'23 event. @jofftiquez 

Thank you sir.

**Comment by 0nikhilkumar** [comment]
@jofftiquez please review pr and merge and give label "hacktoberfest-accepted"

**Review by jofftiquez — CHANGES_REQUESTED** [review]
See https://github.com/OSSPhilippines/freefolio/pull/117#issuecomment-1760053691

**Comment by 0nikhilkumar** [comment]
Sir Changes are done @jofftiquez @jofftiquez

**Comment by 0nikhilkumar** [comment]
Sir I am hacktoberfest'23 participants so please merge this Pull Request and give the label of "hacktoberfest-accepted" then its counted for merging 1PR in hacktoberfest'23 event. @jofftiquez 

Thank you sir.

**Review by jofftiquez — APPROVED** [review]
LGTM, thanks

**Comment by jofftiquez** [comment]
Thank you for your contribution @0nikhilkumar 💪🏼

**Pull request merged**
