### PR TITLE
Add favicon to some templates

### PR DESCRIPTION
**Pull request by fidellim**
Add favicons to the following templates:
- Plain
- Outlines
- Basic

<details><summary>Click to view favicons</summary>
<p>

image
image
image

</p>
</details>

### CODE REVIEW

**Comment by jofftiquez** [comment]
Hi thanks for this @fidellim. I'm all up for adding favicon, however, I think it would be better to match the color of the favicon to the general theme of the template

**Comment by fidellim** [comment]
> Hi thanks for this @fidellim. I'm all up for adding favicon, however, I think it would be better to match the color of the favicon to the general theme of the template

Sure sir @jofftiquez! Will update it asap 👍🏻

**Comment by fidellim** [comment]
# Update favicons of the following templates:

- Plain
- Outlines
- Basic

<details><summary>Click to view changes</summary>
<p>

image
image
image

</p>
</details>

**Review by jofftiquez — APPROVED** [review]
This is better, thanks

**Pull request merged**
