### PR TITLE
Add ES linters

### PR DESCRIPTION
**Pull request by tahseenzahra**
This pr includes 

- the files to check the linters error in the code
- instructions to install and check errors on the local system

### CODE REVIEW

**Comment by mpotane** [comment]
too many files siguro gitignore nalang yung node_modules folder.

**Comment by tahseenzahra** [comment]
> too many files siguro gitignore nalang yung node_modules folder.

Done @mpotane

**Comment by jofftiquez** [comment]
> too many files siguro gitignore nalang yung node_modules folder.

Hello thank you for the suggestion, very helpful! 

May I just ask the we keep the conversation in this repo exclusively English for the interest of non-Filipino speakers. Thank  you <3

**Comment by jofftiquez** [comment]
Hello @tahseenzahra I didn't realize that there's already a PR for #25, can you review it and add your improvements? Closing this for duplicate. Thanks.

https://github.com/OSSPhilippines/freefolio/pull/41

**Pull request closed without merging**
