### PR TITLE
Add animation on scroll to template sites

### PR DESCRIPTION
**Pull request by fidellim**
- Add animation to all template sites
- Tested on different screen sizes as well

Reference of the issue: https://github.com/OSSPhilippines/freefolio/issues/78

<details>
<summary>Click to view changes</summary>

#### Part 1
https://user-images.githubusercontent.com/26820513/227697973-8a6dbb9b-f11c-4bb5-8fdd-e2808a1eb043.mp4

#### Part 2
https://user-images.githubusercontent.com/26820513/227697974-4f41159c-8833-4abe-91e7-b3318a3520e8.mp4

#### Part 3
https://user-images.githubusercontent.com/26820513/227697977-c566db28-09bc-4923-9301-9c5cccd46216.mp4

#### Part 4
https://user-images.githubusercontent.com/26820513/227697978-543b49e2-0637-4336-9910-9f2888d401d5.mp4

</details>

### CODE REVIEW

**Comment by fidellim** [comment]
Hello! Just have a question. If the issue has been resolved, who will be the one to close it? Is it the one who posted the issue or the maintainer of the project?

**Comment by jofftiquez** [comment]
> Hello! Just have a question. If the issue has been resolved, who will be the one to close it? Is it the one who posted the issue or the maintainer of the project?

Hello you may reference the issues to the PR so that GitHub can close it automatically on PR closed event. 

Thank you for this PR!

**Review by jofftiquez — APPROVED** [review]
Looks good, thank you

**Comment by fidellim** [comment]
> > Hello! Just have a question. If the issue has been resolved, who will be the one to close it? Is it the one who posted the issue or the maintainer of the project?
> 
> Hello you may reference the issues to the PR so that GitHub can close it automatically on PR closed event.
> 
> Thank you for this PR!

Hello, I would just like to confirm if this is the way to reference it? [Click link here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by jofftiquez** [comment]
> Hello, I would just like to confirm if this is the way to reference it? [Click link here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

Yes that is correct. 

E.g.`Closes #80` `Resolves #12` etc.

**Comment by fidellim** [comment]
> > Hello, I would just like to confirm if this is the way to reference it? [Click link here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
> 
> Yes that is correct.
> 
> E.g.`Closes #80` `Resolves #12` etc.

Thanks sir @jofftiquez.

**Pull request merged**
